all:
	cd userpf; make $@
	cd mgmtpf; make $@
	cd efxmgmt; make $@

install:
	cd userpf; make $@
	cd mgmtpf; make $@
	cd efxmgmt; make $@

clean:
	cd userpf; make $@
	cd mgmtpf; make $@
	cd efxmgmt; make $@
